/***************************************************************************
Copyright 2017 Hewlett Packard Enterprise Development LP.
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE. See the GNU General Public License for more details. You
should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation,
Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
***************************************************************************/

#define _MSG_TOC	"Table of Contents"
#define _MSG_LINK	"Link to Notes and Warnings"
#define _MSG_NEXT_NOTE  "[Next]"
#define _MSG_1_0	"1.0 What is it doing?"
#define _MSG_1_1	"1.1 Global CPU Usage Counters"
#define _MSG_1_1_1      "1.1.1 Global CPU Usage by CPU"
#define _MSG_1_1_2      "1.1.2 Global CPU Usage by LDOM"
#define _MSG_1_1_3      "1.1.3 Power Savings Report" 
#define _MSG_1_1_4      "1.1.4 Hyperthread CPU Usage" 
#define _MSG_1_2	"1.2 CPU Usage by Task"  
#define _MSG_1_2_1	"1.2.1 Top Tasks sorted by Run Time"
#define _MSG_1_2_2	"1.2.2 Top Tasks sorted by System Time"
#define _MSG_1_2_3	"1.2.3 Top Tasks sorted by Steal Time"
#define _MSG_1_3	"1.3 Frequency of trace types..."
#define _MSG_1_3_1	"1.3.1 Global Trace events"
#define _MSG_1_3_2      "1.3.2 Per-Task Trace events"
#define _MSG_1_3_3      "1.3.3 Trace Events of Top 10 Processes" 
#define _MSG_1_4 	"1.4 Reports from HARDCLOCK traces"
#define _MSG_1_4_1	"1.4.1 Report of cpu states at clock tick"
#define _MSG_1_4_2	"1.4.2 Report of each CPU's state at clock tick"    
#define _MSG_1_4_3	"1.4.3 Report of non-idle kernel functions at each clock tick"
#define _MSG_1_4_4	"1.4.4 Report of non-idle kernel stack traces at each clock tick"       
#define _MSG_1_4_5	"1.4.5 Breakdown of functions by Top 5 PIDs"       
#define _MSG_1_5	"1.5 Thundering Herd Detection"
#define _MSG_1_6	"1.6 Interrupt Request Queue (IRQ) Report"
#define _MSG_1_6_1	"1.6.1 Top Hard IRQ Events"
#define _MSG_1_6_2	"1.6.2 Top Hard IRQ Events Per CPU"
#define _MSG_1_6_3	"1.6.3 Top Soft IRQ Events"

#define _MSG_2_0	"2.0 What is it waiting for?"
#define _MSG_2_1	"2.1 Kernel sleep functions (SWITCH)"
#define _MSG_2_1_1	"2.1.1 Global Kernel sleep functions (SWITCH)"
#define _MSG_2_1_2	"2.1.2 Global Kernel sleep stacktraces (SWITCH)"
#define _MSG_2_1_3	"2.1.3 Per Thread SWTCH reports"
#define _MSG_2_1_4	"2.1.4 Kernel Sleep Functions of Top 10 Threads"
#define _MSG_2_2	"2.2 System-wide RUNQ statistics (waiting for CPU)"
/* #define _MSG_2_2_1	"2.2.1 RUNQ latency histogram (in Usecs)" */
#define _MSG_2_2_1	"2.2.1 RUNQ latency stats per CPU (in Usecs)"
#define _MSG_2_2_2	"2.2.2 Top Threads Waiting on CPU (in secs)"
#define _MSG_2_3	"2.3 Futex statistics"
#define _MSG_2_3_1	"2.3.1 Futex Operation & PID summary (sorted by Count)"
#define _MSG_2_3_2	"2.3.2 Futex Operation & PID summary (sorted by ElpTime)"
#define _MSG_2_3_3	"2.3.3 Futex requeued addr Statistics"
#define _MSG_2_3_4	"2.3.4 Futex Process shared Addrs Statistics"
#define _MSG_3_0	"3.0 File Activity"
#define _MSG_3_1	"3.1 Top Files sorted by Syscall Count"
#define _MSG_3_2	"3.2 Top Files sorted by Elapsed Time"
#define _MSG_3_3	"3.3 Top 10 Files w/ Errors"
#define _MSG_3_4	"3.4 Top Files (Detail)"
#define _MSG_4_0	"4.0 Device Report"
#define _MSG_4_1	"4.1 Global IO Statistics"
#define _MSG_4_2	"4.2 Per-Device Statistics"
#define _MSG_4_2_1      "4.2.1 Most Active Disks (Top 10)"
#define _MSG_4_2_2      "4.2.2 Disks with highest Service Times (>5 ios/sec)"
#define _MSG_4_2_3      "4.2.3 Disks with highest Service Times (<5 ios/sec)"
#define _MSG_4_2_4      "4.2.4 Disks with highest Queue Wait Times (Top 10)"
#define _MSG_4_2_5      "4.2.5 Disks with Requeues"
#define _MSG_4_2_6      "4.2.6 Disk Response Time Histogram"
#define _MSG_4_3	"4.3 Device-Mapper Statistics"
#define _MSG_4_3_1	"4.3.1 Most Active Device-mapper devices (Top 10)"
#define _MSG_4_3_2	"4.3.2 Device-mapper devices with highest Service Times (>5 ios/sec)"
#define _MSG_4_4	"4.4 FC HBA Statistics (for multipath devices)"
#define _MSG_4_5	"4.5 Target WWN Statistics (for FC storage arrays)"
#define _MSG_4_6	"4.6 Tasks doing Multipath Active I/O (Top 10)"
#define _MSG_4_7	"4.7 Tasks doing Active I/O (Top 10)"
#define _MSG_4_8	"4.8 Disk block read frequency"
#define _MSG_4_9	"4.9 Disk block write frequency"
#define _MSG_5_0	"5.0 Network Statistics"
#define _MSG_5_1  	"5.1 Top IP->IP dataflows"
#define _MSG_5_2	"5.2 Remote IP Activity (Top 10)"
#define _MSG_5_3	"5.3 Top 5 ports on Active Remote IP Addresses"
#define _MSG_5_4	"5.4 Local IP Activity (Top 10)"
#define _MSG_5_5	"5.5 Top 5 ports on Active Local IP Addresses"
#define _MSG_5_6 	"5.6 Top 10 Active Socket Connections"
#define _MSG_6_0	"6.0 Process Memory Statistics"
#define _MSG_6_1	"6.1 Top Processes sorted by Resident Set Size (RSS)"
#define _MSG_6_2	"6.2 Top Processes sorted by Virtual Set Size (VSS)"
#define _MSG_7_0	"7.0 Oracle Analysis"
#define _MSG_7_1	"7.1 Oracle Instances"
#define _MSG_7_2	"7.2 Oracle Log Writer Analysis"
#define _MSG_7_3	"7.3 Oracle Archive Log Analysis"
#define _MSG_7_4	"7.4 Oracle DB Writer Analysis"
#define _MSG_7_5	"7.5 Oracle Parallel Query Analysis"
#define _MSG_7_6	"7.6 Oracle Server Process Analysis"
#define _MSG_7_7	"7.7 Oracle IO Slave Analysis"
#define _MSG_8_0	"8.0 Docker Containers"
#define _MSG_8_1	"8.1 Docker PS listing"
#define _MSG_8_2	"8.2 Docker CPU usage"
#define _MSG_8_3	"8.3 Docker IO usage"
#define _MSG_9_0	"9.0 File Links"
#define _MSG_9_1	"9.1 Report Files"
#define _MSG_9_2	"9.2 CSV Files"
#define _MSG_9_3	"9.3 Supplemental Files"
#define _MSG_9_4	"9.4 Visualization Files"
#define _MSG_10_0	"10.0 Warnings"
