/***************************************************************************
Copyright 2017 Hewlett Packard Enterprise Development LP.
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE. See the GNU General Public License for more details. You
should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation,
Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
***************************************************************************/

#define _LNK_TOC	"TOC"
#define _LNK_WARN	"warncheck"
#define _LNK_0_1_0	"cmdline"
#define _LNK_0_2_0	"sca_vuln"
#define _LNK_0_3_0      "clocksource"
#define _LNK_1_0	"Section1"
#define _LNK_1_1	"subsection1.1"
#define _LNK_1_1_1	"subsection1.1.1"
#define _LNK_1_1_2	"subsection1.1.2"
#define _LNK_1_1_3	"subsection1.1.3"
#define _LNK_1_1_4	"subsection1.1.4"
#define _LNK_1_2	"subsection1.2"
#define _LNK_1_2_1	"subsection1.2.1"
#define _LNK_1_2_2	"subsection1.2.2"
#define _LNK_1_2_3	"subsection1.2.3"
#define _LNK_1_2_4	"subsection1.2.4"
#define _LNK_1_3	"subsection1.3"
#define _LNK_1_3_1	"subsection1.3.1"
#define _LNK_1_3_2	"subsection1.3.2"
#define _LNK_1_3_3	"subsection1.3.3"
#define _LNK_1_4	"subsection1.4"
#define _LNK_1_4_1	"subsection1.4.1"
#define _LNK_1_4_2	"subsection1.4.2"
#define _LNK_1_4_3	"subsection1.4.3"
#define _LNK_1_4_4	"subsection1.4.4"
#define _LNK_1_4_5	"subsection1.4.5"
#define _LNK_1_4_6	"subsection1.4.6"
#define _LNK_1_5	"subsection1.5"
#define _LNK_1_6	"subsection1.6"
#define _LNK_1_6_1	"subsection1.6.1"
#define _LNK_1_6_2	"subsection1.6.2"
#define _LNK_1_6_3	"subsection1.6.3"
#define _LNK_1_7	"subsection1.7"
#define _LNK_1_7_1	"subsection1.7.1"
#define _LNK_1_7_2	"subsection1.7.2"
#define _LNK_2_0	"Section2"
#define _LNK_2_1	"subsection2.1"
#define _LNK_2_1_1	"subsection2.1.1"
#define _LNK_2_1_2	"subsection2.1.2"
#define _LNK_2_1_3	"subsection2.1.3"
#define _LNK_2_1_4	"subsection2.1.4"
#define _LNK_2_2	"subsection2.2"
#define _LNK_2_2_1	"subsection2.2.1"
#define _LNK_2_2_2	"subsection2.2.2"
#define _LNK_2_2_3	"subsection2.2.3"
#define _LNK_2_3	"subsection2.3"
#define _LNK_2_3_1	"subsection2.3.1"
#define _LNK_2_3_2	"subsection2.3.2"
#define _LNK_2_3_3	"subsection2.3.3"
#define _LNK_2_3_4	"subsection2.3.4"
#define _LNK_3_0	"Section3"
#define _LNK_3_1	"subsection3.1"
#define _LNK_3_2	"subsection3.2"
#define _LNK_3_3	"subsection3.3"
#define _LNK_3_4	"subsection3.4"
#define _LNK_4_0	"Section4"
#define _LNK_4_1	"subsection4.1"
#define _LNK_4_2	"subsection4.2"
#define _LNK_4_2_1	"subsection4.2.1"
#define _LNK_4_2_2	"subsection4.2.2"
#define _LNK_4_2_3	"subsection4.2.3"
#define _LNK_4_2_4	"subsection4.2.4"
#define _LNK_4_2_5	"subsection4.2.5"
#define _LNK_4_2_6	"subsection4.2.6"
#define _LNK_4_3	"subsection4.3"
#define _LNK_4_3_1	"subsection4.3.1"
#define _LNK_4_3_2	"subsection4.3.2"
#define _LNK_4_4	"subsection4.4"
#define _LNK_4_5	"subsection4.5"
#define _LNK_4_6	"subsection4.6"
#define _LNK_4_7	"subsection4.7"
#define _LNK_4_8	"subsection4.8"
#define _LNK_4_9	"subsection4.9"
#define _LNK_4_10	"subsection4.10"
#define _LNK_5_0	"Section5"
#define _LNK_5_1	"Section5.1"
#define _LNK_5_2	"Section5.2"
#define _LNK_5_3	"Section5.3"
#define _LNK_5_4	"Section5.4"
#define _LNK_5_5	"Section5.5"
#define _LNK_5_6	"Section5.6"
#define _LNK_5_7	"Section5.7"
#define _LNK_6_0	"Section6"
#define _LNK_6_1	"subsection6.1"
#define _LNK_6_2	"subsection6.2"
#define _LNK_6_3	"subsection6.3"
#define _LNK_7_0	"Section7"
#define _LNK_7_1	"subsection7.1"
#define _LNK_7_2	"subsection7.2"
#define _LNK_7_3	"subsection7.3"
#define _LNK_7_4	"subsection7.4"
#define _LNK_7_5	"subsection7.5"
#define _LNK_7_6	"subsection7.6"
#define _LNK_7_7	"subsection7.7"
#define _LNK_8_0	"Section8"
#define _LNK_8_1	"subsection8.1"
#define _LNK_8_2	"subsection8.2"
#define _LNK_8_3	"subsection8.3"
#define _LNK_9_0	"Section9"
#define _LNK_9_1	"subsection9.1"
#define _LNK_9_2	"subsection9.2"
#define _LNK_9_3	"subsection9.3"
#define _LNK_9_4	"subsection9.4"
#define _LNK_10_0	"Section10"

#define _HTTP_BARRIERS "BarrierWritesOracleASM.htm"
#define _HTTP_SEMGET "SAPDB2semget.htm"
#define _HTTP_NUMA_BALANCING "numa_balancing.htm"
#define _HTTP_UNTERMINATED_IXGBE "UnterminatedIxgbe.htm"
#define _HTTP_NUMA_OFF "numa_off.htm"
#define _HTTP_SEMLOCK "SemaphoreScaling.htm"
#define _HTTP_XFS_DIO_UNALIGNED "OracleLGWRwithXFS.htm"
#define _HTTP_XFS_DIOREAD "XfsDirectIOReadPerf.htm"
#define _HTTP_TASKLET "TaskletIRQs.htm"
#define _HTTP_POWER "power_vs_perf.htm"
#define _HTTP_MULTIPATH_BUG "multipath_bug.htm"
#define _HTTP_SK_BUSY "sk_busy_loop.htm"
#define _HTTP_ADD_RANDOM "add_random.htm"
#define _HTTP_MD_FLUSH "md_flush.htm"
#define _HTTP_HUGETLB_FAULT "hugetlb_fault.htm"
#define _HTTP_KSTAT_IRQS "kstat_irqs.htm"
#define _HTTP_ORACLE_POLL "oracle_polling.htm"
#define _HTTP_PCC_CPUFREQ "pcc_cpufreq.htm"
#define _HTTP_SSA_VULN "sca_vuln.htm"
#define _HTTP_TCP_TIMEOUTS "tcp_timeouts.htm"
#define _HTTP_KVM_PAGEFAULT "kvm_pagefault.htm"
#define _HTTP_SQL_STATS "sql_stats.htm"
#define _HTTP_ORACLE_COLSTATS "oracle_colstats.htm"
#define _HTTP_CACHE_BYPASS "cache_bypass.htm"
#define _HTTP_RUNQ_DELAYS "runq_delays.htm"
#define _HTTP_LARGE_NUMA_NODE "large_numa_node.htm"
#define _HTTP_CLOCKSOURCE "clocksource.htm"
#define _HTTP_SYSTEMD_USER "systemd_user.htm"
#define _HTTP_MEMBLOCK_ALLOC "memblock_alloc.htm"
#define _HTTP_4_5 "#subsection4.5"

#define _MSG_LINK_INFO \
	"Kparse runs several standard checks on the ki data and highlights\nconditions that indicate a problem or issue that may require further\ninvestigation.  Each check is linked through a Note or Warning link."

#define _MSG_1_0_KEY \
	" Key: All times are in seconds\n ElapsedT    the total wall clock time for the system call during the trace\n Max         the longest time the call took during the trace\n Min         the shortest time the call took during the trace\n Ave         the average time the call took during the trace\n SystemtT    the total time spent in the OS for the systemcall during the trace"

#define _MSG_1_4_INFO \
	" traces are generated at each clock tick (every 10 ms) and can\ngive us a rough profile of system activity.\nIdle traces may not be collected while in a power savings state.  Missing\ndistort the percentages."

#define _MSG_1_5_INFO \
	" trace are generated from the kernel function setrq() which\nputs threads on the run queue.  The trace provides the name of the\ncalling function and can provide insight in kernel scheduling.\n\n"

#define _MSG_4_8_INFO \
	"Note:  If the same physical block is read more than 20 during the kitrace sample,\nit could be the result of excessive read ahead or inefficient buffer cache utilization.\n"

#define _MSG_5_2_INFO \
	"Errors on open, stat, or access calls might be the result of an inefficient path search order\n"

#define _MSG_6_7_INFO \
	"Note: Checking pids with an I/O count greater than 250 for more physical read I/O\nthan logical read I/O.  "

#define _MSG_6_7_INFO2 \
	"Red lines indicate that physical read IO exceeds logical IO by 50%% or more\nBrown lines indicate that physical read IO exceeds logical IO by 20-50%%\nBlack lines indicate that physical read IO is less than 20%% greater than logical IO"
