#!/bin/bash
#
# Stops the user's linuxki Docker container, if it is running.

container="$USER-linuxki"

if docker ps -f name=$container 2>/dev/null | grep -q $container; then
        docker stop $container
fi
