.\" Process this file with
.\" groff -man -Tascii kiinfo.1
.\"
.ad l
.TH kivis-stop 1 "7.3 - December 21, 2021" version "7.3"
.SH NAME
kivis-stop \- Stop the LinuxKI visualization Docker container

.SH SYNOPSIS
.B kivis-stop

.SH DESCRIPTION

.B kivis-stop
stops the Docker container
.BR linuxki ,
which is used by the LinuxKI visualization tools. The container is only stopped if it is running so it is not an error to run this command when the container is not running.

.SH AUTHOR
Christopher Voltz <christopher@voltz.ws>

.SH SEE ALSO
.BR LinuxKI (1),
.BR kiinfo-dump (1),
.BR kiinfo-likidump (1),
.BR kiinfo-likimerge (1),
.BR kiinfo-live (1),
.BR kiinfo-kparse (1),
.BR kiinfo-kitrace (1),
.BR kiinfo-kipid (1),
.BR kiinfo-kiprof (1),
.BR kiinfo-kidsk (1),
.BR kiinfo-kirunq (1),
.BR kiinfo-kiwait (1),
.BR kiinfo-kifile (1),
.BR kiinfo-kisock (1),
.BR kiinfo-kifutex (1),
.BR kiinfo-kidock (1),
.BR kiinfo-kiall (1),
.BR kiinfo-clparse (1),
.BR runki (1),
.BR kiall (1),
.BR kiclean (1),
.BR kivis-build (1),
.BR kivis-start (1),
.BR kivis-stop (1)

.UR https://github.com/HewlettPackard/LinuxKI/wiki
.UE
